import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AuditReport } from './fssai-engine';

export async function generatePDF(report: AuditReport): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(27, 94, 32); // #1B5E20 - FSSAI Green
  doc.rect(0, 0, pageWidth, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('FoodSafe AI — Inspection Report', 15, 17);
  
  // Assessment Summary
  doc.setTextColor(33, 33, 33);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString()}`, 15, 35);
  
  // Score Box
  doc.setFillColor(245, 245, 245);
  doc.rect(15, 45, 180, 40, 'F');
  
  doc.setFontSize(32);
  doc.setTextColor(27, 94, 32);
  doc.text(`${report.overallScore}/100`, 25, 65);
  
  doc.setFontSize(14);
  doc.setTextColor(33, 33, 33);
  doc.text(`Risk Level: ${report.riskLevel.toUpperCase()}`, 25, 75);
  
  doc.setFontSize(12);
  doc.text(`Estimated Fix Cost: ${new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(report.estimatedTotalFixCostInr)}`, 110, 65);
  doc.text(`Estimated Timeline: ${report.estimatedFixTimeline}`, 110, 75);

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 15, 100);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const splitSummary = doc.splitTextToSize(report.summary, 180);
  doc.text(splitSummary, 15, 107);

  // Category Table
  autoTable(doc, {
    startY: 130,
    head: [['Category', 'Score', 'Compliance Rate']],
    body: report.categories.map(c => [
      c.name.replace(/_/g, ' '), 
      `${c.score}%`, 
      `${c.compliantCount}/${c.totalParameters}`
    ]),
    theme: 'striped',
    headStyles: { fillColor: [27, 94, 32] }
  });

  // Violations Table
  if (report.violations.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Identified Violations', 15, 20);
    
    autoTable(doc, {
      startY: 25,
      head: [['Severity', 'Parameter', 'Observation', 'Remediation', 'Est. Cost']],
      body: report.violations.map(v => [
        v.severity.toUpperCase(),
        v.parameter,
        v.observation,
        v.remediation,
        `INR ${v.estimatedCost}`
      ]),
      styles: { fontSize: 8 },
      columnStyles: {
        0: { fontStyle: 'bold' },
        3: { cellWidth: 50 },
        2: { cellWidth: 50 }
      },
      headStyles: { fillColor: [211, 47, 47] } // #D32F2F - Danger Red
    });
  }

  // Footer & Signature
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    if (i === pageCount) {
      const finalY = (doc as any).lastAutoTable?.finalY || 150;
      doc.setFontSize(10);
      doc.setTextColor(33, 33, 33);
      doc.setFont('helvetica', 'bold');
      doc.text('Authorized Inspector Signature:', 15, finalY + 30);
      doc.line(15, finalY + 45, 80, finalY + 45);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.text('Digitally Verified by FoodSafe AI Engine', 15, finalY + 50);
    }

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by FoodSafe AI | Aura Architects | IIM Bangalore',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc.output('blob');
}
